/**
 * Copyright (c) 2013 by InstantSuggest.com
 * Released under GPL2 License, see http://www.gnu.org/licenses/gpl-2.0.html
 * For contribution, see http://www.instantsuggest.com/contribution
 * For contacting, see http://www.instantsuggest.com/contact
 */
(function(){if("object"!==typeof window.InstantSuggest){var a=window,b=window,c;var d=["instantsuggest.js","instantsuggest.min.js"];if(null===d||void 0===d||""===d)c="";else{"string"===typeof d&&(d=[d]);c="";for(var e=0;e<d.length;e++)0<e&&(c+="|"),c+=d[e];for(var d="",e=document.getElementsByTagName("script"),f=0;f<e.length;f++){var g=e[f].src.match(RegExp("(^|.*?[\\\\/])(?:"+c+")(?:\\?.*)?$","i"));if(g&&2<=g.length){d=g[1];break}}-1==d.indexOf("://")&&(d=0===d.indexOf("/")?location.href.match(/^.*?:\/\/[^\/]*/)[0]+
d:location.href.match(/^[^\?]*\//)[0]+d);c=d}a.$IS=b.InstantSuggest={version:"2.0.1",pluginName:"InstantSuggest",helpLink:"http://www.instantsuggest.com/documentation/user-guide",basePath:c}}})();
(function(){"object"===typeof window.InstantSuggest&&($IS.Ajax={callbackCount:0,param:function(a){var b=[],c=function(a,c){c="function"===typeof c?c():null==c?"":c;"boolean"===typeof c&&(c=c?1:0);b[b.length]=encodeURIComponent(a)+"="+encodeURIComponent(c)},d=function(a,b){if("object"===typeof b)if(void 0!==b.length)for(var g=0;g<b.length;g++)/\[\]$/.test(a)?c(a,b[g]):d(a+"["+("object"===typeof b[g]?g:"")+"]",b[g]);else for(g in b)d(a+"["+g+"]",b[g]);else c(a,b)};for(name in a)a.hasOwnProperty(name)&&
d(name,a[name]);return b.join("&").replace(/%20/g,"+")},parseJson:function(a){if("object"===typeof a)return a;if("function"===typeof a)return a();if(JSON&&JSON.parse)return JSON.parse(a);if(null===a)return a;if("string"===typeof a&&(a=a.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,""))&&/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[\da-fA-F]{4})/g,"@").replace(/"[^"\\\r\n]*"|true|false|null|-?(?:\d+\.|)\d+(?:[eE][+-]?\d+|)/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return(new Function("return "+
a))();throw"Invalid JSON data";},loadScript:function(a){var b=!1,c=document.createElement("script");c.type="text/javascript";c.async=a.async;c.src=a.url;c.onload=c.onreadystatechange=function(){if(!b&&(!this.readyState||"loaded"===this.readyState||"complete"===this.readyState))if(b=!0,c.onload=c.onreadystatechange=null,c&&(c.parentNode&&a.remove)&&c.parentNode.removeChild(c),"function"===typeof a.onload)a.onload()};c.onerror=function(b){c.onerror=null;c&&(c.parentNode&&a.remove)&&c.parentNode.removeChild(c);
if("function"===typeof a.onerror)a.onerror('Error loading url "'+a.url+'": '+b)};document.getElementsByTagName("head")[0].appendChild(c)},jsonp:function(a){var b=$IS.Tools.extend({url:"",data:{},callback:!1,async:!0,success:function(a){},error:function(a){},complete:function(){},beforeSend:function(){},timeout:7},a,!0),c=b.callback?b.callback:"cb"+(new Date).getTime();a=b.url+(/\?/.test(b.url)?"":"?");var d=null,e=[window],f=this.param(b.data);f&&(a.indexOf("?")<a.length-1&&(a+="&"),a+=f);b.callback||
(a.indexOf("?")<a.length-1&&(a+="&"),a+="callback="+c);c=c.split(".");for(f=0;f<c.length-1;f++){var g=c[f],h=e[f];"object"!==typeof h[g]&&"function"!==typeof h[g]&&(h[g]={});e.push(h[g])}var k=e[e.length-1],l=c[c.length-1],n=setTimeout(function(){m();b.error("Timed out")},1E3*b.timeout),m=function(){clearTimeout(n);try{delete k[l]}catch(a){}k[l]=null;b.complete()};"function"!==typeof k[l]&&(k[l]=function(a){m();try{d=$IS.Ajax.parseJson(a)}catch(c){b.error(c.message);return}null!=d&&b.success(d)});
b.beforeSend();this.loadScript({url:a,async:b.async,remove:!0,onload:null,onerror:function(a){m();b.error(a)}});return d}})})();
(function(){if("object"===typeof window.InstantSuggest){var a=function(a){var c=location.host.toLowerCase().split("."),d="com";if(0<c.length&&(c=c[c.length-1],"fvdh"==c||"fvdw"==c))d=c;return"http://api.instantsuggest."+d+a};$IS.Api={cache:{},log:function(b,c,d,e){var f=a("/client/get?"),f=f+$IS.Ajax.param({c:$IS.Env.client,p:$IS.Env.platform,e:$IS.Env.editor,v:$IS.version,t:b.type,x:c,a:b.params,o:b.preference.getAllOptionValues(),q:b.suggestionUrl,r:d&&d.length?1:0}),g=f.toLowerCase();void 0!==
this.cache[g]?e&&e(this.cache[g]):$IS.Ajax.jsonp({url:f,async:!0,success:function(a){$IS.Api.cache[g]=a;e&&e(a)}})}}}})();(function(){"object"===typeof window.InstantSuggest&&($IS.Env={client:location.hostname.toLowerCase(),platform:"",editor:""})})();
(function(){"object"===typeof window.InstantSuggest&&($IS.Event={KEY:{A:65,E:69,I:73,K:75,O:79,M:77,S:83,V:86,LEFT:37,RIGHT:39},listeners:{},on:function(a,b){this.listeners[a]=b},fire:function(a,b){if(this.listeners[a])this.listeners[a](b)},getMouseButton:function(a){return void 0!=a.which&&null!=a.which?a.which:!a.which&&void 0!==a.button?a.button&1?1:a.button&2?3:a.button&4?2:0:0},getKey:function(a){return a.keyCode||a.which||a.charCode},getTarget:function(a){return a.target||a.srcElement||a.originalTarget},
domReady:function(){function a(){try{document.addEventListener?(document.removeEventListener("DOMContentLoaded",a,!1),b()):document.attachEvent&&"complete"===document.readyState&&(document.detachEvent("onreadystatechange",a),b())}catch(c){}}function b(){for(var a;a=c.shift();)a()}var c=[];return function(b){c.push(b);"complete"===document.readyState&&setTimeout(a,1);if(1==c.length)if(document.addEventListener)document.addEventListener("DOMContentLoaded",a,!1),window.addEventListener("load",a,!1);
else if(document.attachEvent){document.attachEvent("onreadystatechange",a);window.attachEvent("onload",a);b=!1;try{b=!window.frameElement}catch(e){}if(document.documentElement.doScroll&&b){var f=function(){try{document.documentElement.doScroll("left")}catch(b){setTimeout(f,1);return}a()};f()}}}}()})})();
(function(){"object"===typeof window.InstantSuggest&&($IS.Google={},$IS.Google.languages=[["Abkhaz","ab"],["Afar","aa"],["Afrikaans","af"],["Akan","ak"],["Albanian","sq"],["Amharic","am"],["Arabic","ar"],["Aragonese","an"],["Armenian","hy"],["Assamese","as"],["Avaric","av"],["Avestan","ae"],["Aymara","ay"],["Azerbaijani","az"],["Bambara","bm"],["Bashkir","ba"],["Basque","eu"],["Belarusian","be"],["Bengali; Bangla","bn"],["Bihari","bh"],["Bislama","bi"],["Bosnian","bs"],["Breton","br"],["Bulgarian",
"bg"],["Burmese","my"],["Catalan; Valencian","ca"],["Chamorro","ch"],["Chechen","ce"],["Chichewa; Chewa; Nyanja","ny"],["Chinese","zh"],["Chuvash","cv"],["Cornish","kw"],["Corsican","co"],["Cree","cr"],["Croatian","hr"],["Czech","cs"],["Danish","da"],["Divehi; Dhivehi; Maldivian;","dv"],["Dutch","nl"],["Dzongkha","dz"],["English","en"],["Esperanto","eo"],["Estonian","et"],["Ewe","ee"],["Faroese","fo"],["Fijian","fj"],["Finnish","fi"],["French","fr"],["Fula; Fulah; Pulaar; Pular","ff"],["Galician",
"gl"],["Georgian","ka"],["German","de"],["Greek, Modern","el"],["Guaran\u00ed","gn"],["Gujarati","gu"],["Haitian; Haitian Creole","ht"],["Hausa","ha"],["Hebrew (modern)","he"],["Herero","hz"],["Hindi","hi"],["Hiri Motu","ho"],["Hungarian","hu"],["Interlingua","ia"],["Indonesian","id"],["Interlingue","ie"],["Irish","ga"],["Igbo","ig"],["Inupiaq","ik"],["Ido","io"],["Icelandic","is"],["Italian","it"],["Inuktitut","iu"],["Japanese","ja"],["Javanese","jv"],["Kalaallisut, Greenlandic","kl"],["Kannada",
"kn"],["Kanuri","kr"],["Kashmiri","ks"],["Kazakh","kk"],["Khmer","km"],["Kikuyu, Gikuyu","ki"],["Kinyarwanda","rw"],["Kyrgyz","ky"],["Komi","kv"],["Kongo","kg"],["Korean","ko"],["Kurdish","ku"],["Kwanyama, Kuanyama","kj"],["Latin","la"],["Luxembourgish, Letzeburgesch","lb"],["Ganda","lg"],["Limburgish, Limburgan, Limburger","li"],["Lingala","ln"],["Lao","lo"],["Lithuanian","lt"],["Luba-Katanga","lu"],["Latvian","lv"],["Manx","gv"],["Macedonian","mk"],["Malagasy","mg"],["Malay","ms"],["Malayalam",
"ml"],["Maltese","mt"],["M\u0101ori","mi"],["Marathi (Mar\u0101\u1e6dh\u012b)","mr"],["Marshallese","mh"],["Mongolian","mn"],["Nauru","na"],["Navajo, Navaho","nv"],["Norwegian Bokm\u00e5l","nb"],["North Ndebele","nd"],["Nepali","ne"],["Ndonga","ng"],["Norwegian Nynorsk","nn"],["Norwegian","no"],["Nuosu","ii"],["South Ndebele","nr"],["Occitan","oc"],["Ojibwe, Ojibwa","oj"],["Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic","cu"],["Oromo","om"],["Oriya","or"],["Ossetian, Ossetic",
"os"],["Panjabi, Punjabi","pa"],["P\u0101li","pi"],["Persian","fa"],["Polish","pl"],["Pashto, Pushto","ps"],["Portuguese","pt"],["Quechua","qu"],["Romansh","rm"],["Kirundi","rn"],["Romanian, Moldavian(Romanian from Republic of Moldova)","ro"],["Russian","ru"],["Sanskrit (Sa\u1e41sk\u1e5bta)","sa"],["Sardinian","sc"],["Sindhi","sd"],["Northern Sami","se"],["Samoan","sm"],["Sango","sg"],["Serbian","sr"],["Scottish Gaelic; Gaelic","gd"],["Shona","sn"],["Sinhala, Sinhalese","si"],["Slovak","sk"],["Slovene",
"sl"],["Somali","so"],["Southern Sotho","st"],["Spanish; Castilian","es"],["Sundanese","su"],["Swahili","sw"],["Swati","ss"],["Swedish","sv"],["Tamil","ta"],["Telugu","te"],["Tajik","tg"],["Thai","th"],["Tigrinya","ti"],["Tibetan Standard, Tibetan, Central","bo"],["Turkmen","tk"],["Tagalog","tl"],["Tswana","tn"],["Tonga (Tonga Islands)","to"],["Turkish","tr"],["Tsonga","ts"],["Tatar","tt"],["Twi","tw"],["Tahitian","ty"],["Uighur, Uyghur","ug"],["Ukrainian","uk"],["Urdu","ur"],["Uzbek","uz"],["Venda",
"ve"],["Vietnamese","vi"],["Volap\u00fck","vo"],["Walloon","wa"],["Welsh","cy"],["Wolof","wo"],["Western Frisian","fy"],["Xhosa","xh"],["Yiddish","yi"],["Yoruba","yo"],["Zhuang, Chuang","za"],["Zulu","zu"]],$IS.Google.domains=[["Afghanistan","https://www.google.com.af"],["Albania","http://www.google.al"],["Algeria","http://www.google.dz"],["American Samoa","http://www.google.as"],["Andorra","https://www.google.ad"],["Angola","http://www.google.co.ao"],["Anguilla","http://www.google.com.ai"],["Antigua and Barbuda",
"https://www.google.com.ag"],["Argentina","http://www.google.com.ar"],["Armenia","http://www.google.am"],["Ascension Island","https://www.google.ac"],["Australia","http://www.google.com.au"],["Austria","https://www.google.at"],["Azerbaijan","http://www.google.az"],["Bahamas","http://www.google.bs"],["Bahrain","http://www.google.com.bh"],["Bangladesh","http://www.google.com.bd"],["Belarus","http://www.google.by/"],["Belgium","http://www.google.be"],["Belize","http://www.google.com.bz"],["Benin","http://www.google.bj"],
["Bolivia","https://www.google.com.bo"],["Bosnia and Herzegovina","http://www.google.ba"],["Botswana","http://www.google.co.bw"],["Brazil","http://www.google.com.br"],["British Indian Ocean Territory","http://www.google.io/"],["British Virgin Islands","http://www.google.vg/"],["Brunei","http://www.google.com.bn"],["Bulgaria","http://www.google.bg"],["Burkina Faso","http://www.google.bf"],["Burundi","http://www.google.bi"],["Cambodia","http://www.google.com.kh"],["Cambodia","http://www.google.com.kh/"],
["Cameroon","http://www.google.cm"],["Canada","http://www.google.ca"],["Cape Verde","http://www.google.cv"],["Catalonia Catalan Countries","http://www.google.cat"],["Central African Republic","http://www.google.cf"],["Chad","http://www.google.td/"],["Chile","http://www.google.cl"],["China","http://www.g.cn"],["China","http://www.google.cn"],["Cocos (Keeling) Islands","http://www.google.cc"],["Colombia","http://www.google.com.co"],["Cook Islands","http://www.google.co.ck"],["Costa Rica","http://www.google.co.cr"],
["Croatia","http://www.google.hr/"],["Cuba","http://www.google.com.cu"],["Cyprus","http://www.google.com.cy"],["Czech Republic","http://www.google.cz"],["Democratic Republic of the Congo","http://www.google.cd"],["Denmark","http://www.google.dk"],["Djibouti","http://www.google.dj"],["Dominica","http://www.google.dm"],["Dominican Republic","http://www.google.com.do"],["Ecuador","http://www.google.com.ec"],["Egypt","http://www.google.com.eg"],["El Salvador","http://www.google.com.sv/"],["Estonia","http://www.google.ee"],
["Ethiopia","http://www.google.com.et"],["Federated States of Micronesia","http://www.google.fm"],["Fiji","http://www.google.com.fj"],["Finland","http://www.google.fi"],["France","http://www.google.fr"],["French Guiana","http://www.google.gf"],["Gabon","http://www.google.ga"],["Gambia","http://www.google.gm/"],["Georgia","http://www.google.ge"],["Germany","http://www.google.de"],["Ghana","http://www.google.com.gh"],["Gibraltar","http://www.google.com.gi"],["Greece","http://www.google.gr/"],["Greenland",
"http://www.google.gl/"],["Guadeloupe","http://www.google.gp/"],["Guatemala","http://www.google.com.gt/"],["Guernsey","http://www.google.gg"],["Guyana","http://www.google.gy/"],["Haiti","http://www.google.ht/"],["Honduras","http://www.google.hn/"],["Hong Kong","http://www.google.com.hk/"],["Hungary","http://www.google.hu/"],["Iceland","http://www.google.is/"],["India","http://www.google.co.in/"],["Indonesia","http://www.google.co.id/"],["Iraq","http://www.google.iq/"],["Ireland","http://www.google.ie/"],
["Isle of Man","http://www.google.im/"],["Israel","http://www.google.co.il/"],["Italy","http://www.google.it/"],["Ivory Coast","http://www.google.ci"],["Jamaica","http://www.google.com.jm/"],["Japan","http://www.google.co.jp/"],["Jersey","http://www.google.je/"],["Jordan","http://www.google.jo/"],["Kazakhstan","http://www.google.kz/"],["Kenya","http://www.google.co.ke/"],["Kiribati","http://www.google.ki/"],["Kuwait","http://www.google.com.kw/"],["Kyrgyzstan","http://www.google.kg/"],["Laos","http://www.google.la/"],
["Latvia","http://www.google.lv/"],["Lebanon","http://www.google.com.lb/"],["Lesotho","http://www.google.co.ls/"],["Libya","http://www.google.com.ly/"],["Liechtenstein","http://www.google.li/"],["Lithuania","http://www.google.lt/"],["Luxembourg","http://www.google.lu/"],["Macedonia","http://www.google.mk/"],["Madagascar","http://www.google.mg/"],["Malawi","http://www.google.mw/"],["Malaysia","http://www.google.com.my/"],["Maldives","http://www.google.mv/"],["Mali","http://www.google.ml/"],["Malta",
"http://www.google.com.mt/"],["Mauritius","http://www.google.mu/"],["Mexico","http://www.google.com.mx/"],["Moldova","http://www.google.md/"],["Mongolia","http://www.google.mn/"],["Montenegro","http://www.google.me/"],["Montserrat","http://www.google.ms/"],["Morocco","http://www.google.co.ma/"],["Mozambique","http://www.google.co.mz/"],["Myanmar","http://www.google.com.mm"],["Namibia","http://www.google.com.na/"],["Nauru","http://www.google.nr/"],["Nepal","http://www.google.com.np/"],["Netherlands",
"http://www.google.nl/"],["New Zealand","http://www.google.co.nz/"],["Nicaragua","http://www.google.com.ni/"],["Niger","http://www.google.ne/"],["Nigeria","http://www.google.com.ng/"],["Niue","http://www.google.nu/"],["Norfolk Island","http://www.google.com.nf/"],["Norway","http://www.google.no/"],["Oman","http://www.google.com.om/"],["Pakistan","http://www.google.com.pk/"],["Palestine","http://www.google.ps/"],["Panama","http://www.google.com.pa/"],["Papua New Guinea","http://www.google.com.pg/"],
["Paraguay","http://www.google.com.py/"],["Peru","http://www.google.com.pe/"],["Philippines","http://www.google.com.ph/"],["Pitcairn Islands","http://www.google.pn/"],["Poland","http://www.google.pl/"],["Portugal","http://www.google.pt/"],["Puerto Rico","http://www.google.com.pr/"],["Qatar","http://www.google.com.qa/"],["Republic of the Congo","http://www.google.cg"],["Romania","http://www.google.ro/"],["Russia","http://www.google.ru/"],["Rwanda","http://www.google.rw/"],["Saint Helena, Ascension and Tristan da Cunha",
"http://www.google.sh/"],["Saint Lucia","http://www.google.com.lc/"],["Saint Vincent and the Grenadines","http://www.google.com.vc/"],["Samoa","http://www.google.ws"],["San Marino","http://www.google.sm/"],["S\u00e3o Tom\u00e9 and Pr\u00edncipe","http://www.google.st/"],["Saudi Arabia","http://www.google.com.sa/"],["Senegal","http://www.google.sn/"],["Serbia","http://www.google.rs/"],["Seychelles","http://www.google.sc/"],["Sierra Leone","http://www.google.com.sl/"],["Singapore","http://www.google.com.sg/"],
["Slovakia","http://www.google.sk/"],["Slovenia","http://www.google.si/"],["Solomon Islands","http://www.google.com.sb/"],["Somalia","http://www.google.so/"],["South Africa","http://www.google.co.za"],["South Korea","http://www.google.co.kr/"],["Spain","http://www.google.es"],["Sri Lanka","http://www.google.lk/"],["Sweden","http://www.google.se/"],["Switzerland","http://www.google.ch"],["Taiwan","http://www.google.com.tw/"],["Tajikistan","http://www.google.com.tj/"],["Tanzania","http://www.google.co.tz/"],
["Thailand","http://www.google.co.th/"],["Timor-Leste","http://www.google.tl/"],["Togo","http://www.google.tg/"],["Tokelau","http://www.google.tk/"],["Tonga","http://www.google.to/"],["Trinidad and Tobago","http://www.google.tt/"],["Tunisia","http://www.google.com.tn/"],["Turkey","http://www.google.com.tr/"],["Turkmenistan","http://www.google.tm/"],["Uganda","http://www.google.co.ug/"],["Ukraine","http://www.google.com.ua/"],["United Arab Emirates","http://www.google.ae"],["United Kingdom","http://www.google.co.uk/"],
["United States Virgin Islands","http://www.google.co.vi/"],["United States","http://www.google.us/"],["Uruguay","http://www.google.com.uy/"],["Uzbekistan","http://www.google.co.uz/"],["Vanuatu","http://www.google.vu"],["Venezuela","http://www.google.co.ve/"],["Vietnam","http://www.google.com.vn/"],["Worldwide","https://www.google.com"],["Zambia","http://www.google.co.zm"],["Zimbabwe","http://www.google.co.zw"]])})();
(function(){"undefined"!=typeof InstantSuggest&&($IS.OptionsDialogModule={commandName:$IS.pluginName+"OptionsDialogCommand",buttonName:$IS.pluginName+"OptionsDialogButton",buttonTitle:$IS.pluginName+" Options (CTRL+SHIFT+O)",buttonIcon:$IS.basePath+"icons/options.png",dialogName:$IS.pluginName+"OptionsDialog",dialogTitle:$IS.pluginName+" Options",params:{}},$IS.StartSelectionModule={commandName:$IS.pluginName+"StartSelectionCommand",buttonName:$IS.pluginName+"StartSelectionButton",buttonTitle:"Start selection (CTRL+SHIFT+S)",
buttonIcon:$IS.basePath+"icons/start-selection.png"},$IS.EndSelectionModule={commandName:$IS.pluginName+"EndSelectionCommand"},$IS.KeywordMenuModule={commandName:$IS.pluginName+"KeywordMenuCommand",buttonName:$IS.pluginName+"KeywordMenuButton",buttonTitle:"Show keyword suggestions (CTRL+SHIFT+E)",buttonIcon:$IS.basePath+"icons/keyword-suggestions.png"},$IS.ContentDialogModule={commandName:$IS.pluginName+"ContentDialogCommand",dialogName:$IS.pluginName+"ContentDialog",dialogTitle:$IS.pluginName+" Toolbox",
params:{},researchKeywords:{}},$IS.KeywordResearchModule={commandName:$IS.pluginName+"KeywordResearchCommand",buttonName:$IS.pluginName+"KeywordResearchButton",buttonTitle:"Open keyword research tool (CTRL+SHIFT+K)",buttonIcon:$IS.basePath+"icons/keyword-tool.png"},$IS.ArticleSearchModule={commandName:$IS.pluginName+"ArticleSearchCommand",buttonName:$IS.pluginName+"ArticleSearchButton",buttonTitle:"Open article search tool (CTRL+SHIFT+A)",buttonIcon:$IS.basePath+"icons/article-tool.png"})})();
(function(){"object"===typeof window.InstantSuggest&&($IS.PreferenceManager={preferences:{},add:function(a){a instanceof $IS.Preference&&(this.preferences[a.name]=a)},get:function(a){return this.preferences[a]?this.preferences[a]:null},each:function(a){if("function"==typeof a)for(var b in this.preferences)if(!1===a(this.preferences[b],b))break},getAllOptionValues:function(){var a={};this.each(function(b,c){a[c]=b.getAllOptionValues()});return a},setAllOptionValues:function(a){this.each(function(b,
c){"object"==typeof a[c]&&b.setAllOptionValues(a[c])})}},$IS.Preference=function(a,b,c){this.name=a;this.displayName=b;this.options={};c=c||[];for(a=0;a<c.length;a++)this.options[c[a].id]=new $IS.Option(c[a])},$IS.Preference.prototype.hasOption=function(a){return"undefined"!=typeof this.options[a]},$IS.Preference.prototype.getOptionValue=function(a){return this.hasOption(a)?this.options[a].getValue():null},$IS.Preference.prototype.setOptionValue=function(a,b){this.hasOption(a)&&this.options[a].setValue(b)},
$IS.Preference.prototype.getAllOptionValues=function(){var a={};this.each(function(b,c){var d=b.getValue();a[c]=d;var e="function"==typeof b.dependencies?b.dependencies():b.dependencies||{};void 0!==e[d]&&(a["_"+c]={},e[d].each(function(b,d){a["_"+c][d]=b.getValue()}))});return a},$IS.Preference.prototype.setAllOptionValues=function(a){this.each(function(b,c){if(void 0!==a[c]){var d=a[c];b.setValue(d);if(void 0!==a["_"+c]){var e="function"==typeof b.dependencies?b.dependencies():b.dependencies||{};
void 0!==e[d]&&e[d].each(function(b,d){var e=a["_"+c][d];void 0!==e&&b.setValue(e)})}}})},$IS.Preference.prototype.each=function(a){if("function"==typeof a)for(var b in this.options)if(!1===a(this.options[b],b))break},$IS.Option=function(a){for(var b in a)this[b]=a[b]},$IS.Option.prototype.getValue=function(){var a=this.value;"checkbox"==this.type&&(a=$IS.Tools.parseBool(a));return a},$IS.Option.prototype.setValue=function(a){var b=a;"checkbox"===this.type&&(b=$IS.Tools.parseBool(a));this.value=b},
$IS.PreferenceManager.add($IS.generalPreference),$IS.keywordToolPreference=new $IS.Preference("keyword","Keyword Tool",[{type:"checkbox",id:"enableKeySelectionMode",label:"Show keyword suggestions when select text by keyboard",value:!1},{type:"checkbox",id:"enableMouseSelectionMode",label:"Show keyword suggestions when select text by mouse",value:!1},{type:"text",id:"minKeywordLength",label:"Minimum keyword length",value:3},{type:"text",id:"maxKeywordLength",label:"Maximum keyword length",value:50},
{type:"select",id:"providerName",label:"Keyword Provider",value:"GoogleAutocomplete",items:function(){var a=[];$IS.keywordProviderManager.each(function(b){a.push([b.displayName,b.name])});return a},dependencies:function(){var a={};$IS.keywordProviderManager.each(function(b){a[b.name]=b.preference});return a}}]),$IS.PreferenceManager.add($IS.keywordToolPreference),$IS.articleToolPreference=new $IS.Preference("article","Article Tool",[{type:"select",id:"providerName",label:"Article Search Service",
value:"GoogleBlogSearch",items:function(){var a=[];$IS.articleProviderManager.each(function(b){a.push([b.displayName,b.name])});return a},dependencies:function(){var a={};$IS.articleProviderManager.each(function(b){a[b.name]=b.preference});return a}}]),$IS.PreferenceManager.add($IS.articleToolPreference))})();
(function(){"object"===typeof window.InstantSuggest&&($IS.ProviderBase=function(a,b,c){this.name=a;this.displayName=b||a;this.preference=new $IS.Preference(a,b,c);this.cache={};this.suggestionUrl="";this.params={}},$IS.ProviderBase.prototype.getSuggestionUrl=function(a){return null},$IS.ProviderBase.prototype.getSearchUrl=function(a){return null},$IS.ProviderBase.prototype.getSuggestions=function(a,b){var c=[],d=this,e=this.suggestionUrl=d.getSuggestionUrl(a),f=e.toLowerCase();this.params=a;void 0!==
d.cache[f]?(c=d.cache[f],"function"===typeof b.success&&b.success(c),"function"===typeof b.complete&&b.complete()):(e=$IS.Tools.extend({url:e,success:function(a){c=d.parseSuggestions(a);d.cache[f]=c;"function"===typeof b.success&&b.success(c)}},b),c=$IS.Ajax.jsonp(e));return c},$IS.ProviderBase.prototype.parseSuggestions=function(a){return a},$IS.ArticleProviderBase=function(a,b,c){this.base=$IS.ProviderBase;this.base(a,b,c);this.type="a";this.pageSize=6},$IS.ArticleProviderBase.prototype=new $IS.ProviderBase,
$IS.KeywordProviderBase=function(a,b,c){this.base=$IS.ProviderBase;this.base(a,b,c);this.type="k"},$IS.KeywordProviderBase.prototype=new $IS.ProviderBase,$IS.ProviderManager=function(a,b){this.type=b;this.providerBaseClass=a;this.providers={}},$IS.ProviderManager.prototype.addProvider=function(a){a instanceof this.providerBaseClass&&(this.providers[a.name]=a)},$IS.ProviderManager.prototype.getProvider=function(a){a||(a=$IS.PreferenceManager.get(this.type).getOptionValue("providerName"));return a?
this.providers[a]:null},$IS.ProviderManager.prototype.each=function(a){if("function"==typeof a)for(var b in this.providers)if(!1===a(this.providers[b],b))break},$IS.articleProviderManager=new $IS.ProviderManager($IS.ArticleProviderBase,"article"),$IS.keywordProviderManager=new $IS.ProviderManager($IS.KeywordProviderBase,"keyword"))})();
(function(){"object"===typeof window.InstantSuggest&&($IS.Tools={extend:function(a){var b=arguments.length,c,d;if("boolean"==typeof(c=arguments[b-1]))b--;else if("boolean"==typeof(c=arguments[b-2]))d=arguments[b-1],b-=2;for(var e=1;e<b;e++){var f=arguments[e],g;for(g in f)if(!0===c||void 0==a[g])if(!d||g in d)a[g]=f[g]}return a},trim:function(a){return null===a||void 0===a?"":(""+a).replace(/^\s*|\s*$/g,"")},formatSuggestion:function(a,b){for(var c,d=0;(c=a.substr(d,1)).match(/\W/);)d++;c==c.toUpperCase()?
b=b.charAt(0).toUpperCase()+(1<b.length?b.substring(1):""):b!=b.toUpperCase()&&(b=b.charAt(0).toLowerCase()+(1<b.length?b.substring(1):""));-1!==a.indexOf(" ",a.length-1)&&(b+=" ");return b},parseBool:function(a){return"false"==a||"0"==a||0==a?!1:(new Boolean(a)).valueOf()},getUrl:function(a,b){},parseUrl:function(a){var b=document.createElement("a");b.href=a;""==b.host&&(b.href=b.href);return b},getTextContent:function(a){return a.innerText||a.textContent||a.innerHTML.replace(/<[^>]*>/g,"")}})})();
(function(){"object"===typeof window.InstantSuggest&&($IS.Wikipedia={},$IS.Wikipedia.languages=[["Abkhazian","ab"],["Acehnese","ace"],["Afar","aa"],["Afrikaans","af"],["Akan","ak"],["Albanian","sq"],["Alemannic","als"],["Amharic","am"],["Anglo-Saxon","ang"],["Arabic","ar"],["Aragonese","an"],["Aramaic","arc"],["Armenian","hy"],["Aromanian","roa-rup"],["Assamese","as"],["Asturian","ast"],["Avar","av"],["Aymara","ay"],["Azerbaijani","az"],["Bambara","bm"],["Banjar","bjn"],["Banyumasan","map-bms"],["Bashkir",
"ba"],["Basque","eu"],["Bavarian","bar"],["Belarusian","be"],["Belarusian (Tara\u0161kievica)","be-x-old"],["Bengali","bn"],["Bihari","bh"],["Bishnupriya Manipuri","bpy"],["Bislama","bi"],["Bosnian","bs"],["Breton","br"],["Buginese","bug"],["Bulgarian","bg"],["Burmese","my"],["Buryat (Russia)","bxr"],["Cantonese","zh-yue"],["Catalan","ca"],["Cebuano","ceb"],["Central_Bicolano","bcl"],["Chamorro","ch"],["Chechen","ce"],["Cherokee","chr"],["Cheyenne","chy"],["Chichewa","ny"],["Chinese","zh"],["Choctaw",
"cho"],["Chuvash","cv"],["Classical Chinese","zh-classical"],["Cornish","kw"],["Corsican","co"],["Cree","cr"],["Crimean Tatar","crh"],["Croatian","hr"],["Czech","cs"],["Danish","da"],["Divehi","dv"],["Dutch","nl"],["Dutch Low Saxon","nds-nl"],["Dzongkha","dz"],["Egyptian Arabic","arz"],["Emilian-Romagnol","eml"],["English","en"],["Erzya","myv"],["Esperanto","eo"],["Estonian","et"],["Ewe","ee"],["Extremaduran","ext"],["Faroese","fo"],["Fiji Hindi","hif"],["Fijian","fj"],["Finnish","fi"],["Franco-Proven\u00e7al/Arpitan",
"frp"],["French","fr"],["Friulian","fur"],["Fula","ff"],["Gagauz","gag"],["Galician","gl"],["Gan","gan"],["Georgian","ka"],["German","de"],["Gilaki","glk"],["Gothic","got"],["Greek","el"],["Greenlandic","kl"],["Guarani","gn"],["Gujarati","gu"],["Haitian","ht"],["Hakka","hak"],["Hausa","ha"],["Hawaiian","haw"],["Hebrew","he"],["Herero","hz"],["Hill Mari","mrj"],["Hindi","hi"],["Hiri Motu","ho"],["Hungarian","hu"],["Icelandic","is"],["Ido","io"],["Igbo","ig"],["Ilokano","ilo"],["Indonesian","id"],["Interlingua",
"ia"],["Interlingue","ie"],["Inuktitut","iu"],["Inupiak","ik"],["Irish","ga"],["Italian","it"],["Japanese","ja"],["Javanese","jv"],["Kabardian Circassian","kbd"],["Kabyle","kab"],["Kalmyk","xal"],["Kannada","kn"],["Kanuri","kr"],["Kapampangan","pam"],["Karachay-Balkar","krc"],["Karakalpak","kaa"],["Kashmiri","ks"],["Kashubian","csb"],["Kazakh","kk"],["Khmer","km"],["Kikuyu","ki"],["Kinyarwanda","rw"],["Kirghiz","ky"],["Kirundi","rn"],["Komi","kv"],["Komi-Permyak","koi"],["Kongo","kg"],["Korean","ko"],
["Kuanyama","kj"],["Kurdish","ku"],["Ladino","lad"],["Lak","lbe"],["Lao","lo"],["Latgalian","ltg"],["Latin","la"],["Latvian","lv"],["Lezgian","lez"],["Ligurian","lij"],["Limburgish","li"],["Lingala","ln"],["Lithuanian","lt"],["Lojban","jbo"],["Lombard","lmo"],["Low Saxon","nds"],["Lower Sorbian","dsb"],["Luganda","lg"],["Luxembourgish","lb"],["Macedonian","mk"],["Malagasy","mg"],["Malay","ms"],["Malayalam","ml"],["Maltese","mt"],["Manx","gv"],["Maori","mi"],["Marathi","mr"],["Marshallese","mh"],["Mazandarani",
"mzn"],["Meadow Mari","mhr"],["Min Dong","cdo"],["Min Nan","zh-min-nan"],["Mingrelian","xmf"],["Mirandese","mwl"],["Moksha","mdf"],["Moldovan","mo"],["Mongolian","mn"],["Muscogee","mus"],["Nahuatl","nah"],["Nauruan","na"],["Navajo","nv"],["Ndonga","ng"],["Neapolitan","nap"],["Nepali","ne"],["Newar / Nepal Bhasa","new"],["Norfolk","pih"],["Norman","nrm"],["North Frisian","frr"],["Northern Sami","se"],["Northern Sotho","nso"],["Norwegian (Bokm\u00e5l)","no"],["Norwegian (Nynorsk)","nn"],["Novial","nov"],
["Occitan","oc"],["Old Church Slavonic","cu"],["Oriya","or"],["Oromo","om"],["Ossetian","os"],["Palatinate German","pfl"],["Pali","pi"],["Pangasinan","pag"],["Papiamentu","pap"],["Pashto","ps"],["Pennsylvania German","pdc"],["Persian","fa"],["Picard","pcd"],["Piedmontese","pms"],["Polish","pl"],["Pontic","pnt"],["Portuguese","pt"],["Punjabi","pa"],["Quechua","qu"],["Ripuarian","ksh"],["Romani","rmy"],["Romanian","ro"],["Romansh","rm"],["Russian","ru"],["Rusyn","rue"],["Sakha","sah"],["Samoan","sm"],
["Samogitian","bat-smg"],["Sango","sg"],["Sanskrit","sa"],["Sardinian","sc"],["Saterland Frisian","stq"],["Scots","sco"],["Scottish Gaelic","gd"],["Serbian","sr"],["Serbo-Croatian","sh"],["Sesotho","st"],["Shona","sn"],["Sichuan Yi","ii"],["Sicilian","scn"],["Silesian","szl"],["Simple English","simple"],["Sindhi","sd"],["Sinhalese","si"],["Slovak","sk"],["Slovenian","sl"],["Somali","so"],["Sorani","ckb"],["Spanish","es"],["Sranan","srn"],["Sundanese","su"],["Swahili","sw"],["Swati","ss"],["Swedish",
"sv"],["Tagalog","tl"],["Tahitian","ty"],["Tajik","tg"],["Tamil","ta"],["Tarantino","roa-tara"],["Tatar","tt"],["Telugu","te"],["Tetum","tet"],["Thai","th"],["Tibetan","bo"],["Tigrinya","ti"],["Tok Pisin","tpi"],["Tongan","to"],["Tsonga","ts"],["Tswana","tn"],["Tumbuka","tum"],["Turkish","tr"],["Turkmen","tk"],["Twi","tw"],["Udmurt","udm"],["Ukrainian","uk"],["Upper Sorbian","hsb"],["Urdu","ur"],["Uyghur","ug"],["Uzbek","uz"],["Venda","ve"],["Venetian","vec"],["Vepsian","vep"],["Vietnamese","vi"],
["Volap\u00fck","vo"],["V\u00f5ro","fiu-vro"],["Walloon","wa"],["Waray-Waray","war"],["Welsh","cy"],["West Flemish","vls"],["West Frisian","fy"],["Western Panjabi","pnb"],["Wolof","wo"],["Wu","wuu"],["Xhosa","xh"],["Yiddish","yi"],["Yoruba","yo"],["Zamboanga Chavacano","cbk-zam"],["Zazaki","diq"],["Zeelandic","zea"],["Zhuang","za"],["Zulu","zu"]])})();
(function(){if("object"===typeof window.InstantSuggest){var a=!1,b=function(){if(!a&&(CKEDITOR.on&&(CKEDITOR.on("instanceCreated",function(a){CKEDITOR.plugins.addExternal($IS.pluginName,$IS.basePath+"plugins/ckeditor4/","plugin.js?ver="+$IS.version);a.editor.on("configLoaded",function(b){a.editor.config.extraPlugins+=","+$IS.pluginName})}),a=!0),a)){var b="CKEditor "+CKEDITOR.version;$IS.Env.editor=$IS.Env.editor?$IS.Env.editor+","+b:b}};"undefined"!=typeof CKEDITOR?b():$IS.Event.domReady(function(){"undefined"!=
typeof CKEDITOR&&b()});var c=!1,d=function(){if(!c){var a=function(a,b){if(!a.plugins[$IS.pluginName]){var c=new tinymce.plugins[$IS.pluginName](a,b);a.plugins[$IS.pluginName]=c;c.init&&c.init(a,b);return!0}return!1};tinymce.onAddEditor&&tinymce.PluginManager?(tinymce.PluginManager.load($IS.pluginName,$IS.basePath+"plugins/tinymce3/plugin.js?ver="+$IS.version),tinymce.onAddEditor.add(function(b,c){a(c,$IS.basePath+"plugins/tinymce3")}),c=!0):tinymce.on&&tinymce.PluginManager&&(tinymce.PluginManager.load($IS.pluginName,
$IS.basePath+"plugins/tinymce4/plugin.js?ver="+$IS.version),tinymce.on("AddEditor",function(b){a(b.editor,$IS.basePath+"plugins/tinymce4")}),c=!0);if(c){var b="TinyMCE "+tinymce.majorVersion+"."+tinymce.minorVersion;$IS.Env.editor=$IS.Env.editor?$IS.Env.editor+","+b:b}}};"undefined"!=typeof tinymce?d():$IS.Event.domReady(function(){"undefined"!=typeof tinymce&&d()})}})();
(function(){"undefined"!=typeof InstantSuggest&&($IS.googleNewsSearchArticleProvider=new $IS.ArticleProviderBase("GoogleBlogSearch","Google Blog Search",[{id:"language",type:"select",label:"Language",value:"en",items:$IS.Google.languages},{id:"domain",type:"select",label:"Country",value:"https://www.google.com",items:$IS.Google.domains}]),$IS.googleNewsSearchArticleProvider.getSuggestionUrl=function(a){var b,c=a.page&&1<a.page?(a.page-1)*this.pageSize:0;b="https://ajax.googleapis.com/ajax/services/search/blogs?v=1.0&hl={language}&rsz={pageSize}&start={start}&q={keyword}".replace("{language}",
this.preference.getOptionValue("language"));b=b.replace("{pageSize}",this.pageSize);b=b.replace("{start}",c);return b=b.replace("{keyword}",encodeURIComponent(a.keyword))},$IS.googleNewsSearchArticleProvider.getSearchUrl=function(a){var b=this.preference.getOptionValue("domain")+"/search?hl={language}&tbm=blg&q={keyword}",b=b.replace("{language}",this.preference.getOptionValue("language"));return b=b.replace("{keyword}",encodeURIComponent(a.keyword))},$IS.googleNewsSearchArticleProvider.parseSuggestions=
function(a){var b=[],c=0;if("object"===typeof a&&a.responseData){if(a.responseData.results)for(var d=0;d<a.responseData.results.length;d++){var e=a.responseData.results[d],f=$IS.Tools.parseUrl(e.blogUrl),f=f.hostname?f.hostname:e.author;b.push({title:e.titleNoFormatting,content:e.content,url:e.postUrl,source:f,date:e.publishedDate})}a.responseData.cursor&&a.responseData.cursor.pages&&(c=a.responseData.cursor.pages.length+1)}return{suggestions:b,maxPage:c}},$IS.articleProviderManager.addProvider($IS.googleNewsSearchArticleProvider))})();
(function(){"undefined"!=typeof InstantSuggest&&($IS.googleNewsSearchArticleProvider=new $IS.ArticleProviderBase("GoogleNewsSearch","Google News Search",[{id:"language",type:"select",label:"Language",value:"en",items:$IS.Google.languages},{id:"domain",type:"select",label:"Country",value:"https://www.google.com",items:$IS.Google.domains}]),$IS.googleNewsSearchArticleProvider.getSuggestionUrl=function(a){var b,c=a.page&&1<a.page?(a.page-1)*this.pageSize:0;b="https://ajax.googleapis.com/ajax/services/search/news?v=1.0&hl={language}&rsz={pageSize}&start={start}&q={keyword}".replace("{language}",
this.preference.getOptionValue("language"));b=b.replace("{pageSize}",this.pageSize);b=b.replace("{start}",c);return b=b.replace("{keyword}",encodeURIComponent(a.keyword))},$IS.googleNewsSearchArticleProvider.getSearchUrl=function(a){var b=this.preference.getOptionValue("domain")+"/search?hl={language}&tbm=nws&q={keyword}",b=b.replace("{language}",this.preference.getOptionValue("language"));return b=b.replace("{keyword}",encodeURIComponent(a.keyword))},$IS.googleNewsSearchArticleProvider.parseSuggestions=
function(a){var b=[],c=0;if(a&&a.responseData){if(a.responseData.results)for(var d=0;d<a.responseData.results.length;d++){var e=a.responseData.results[d];b.push({title:e.titleNoFormatting,content:e.content,url:e.unescapedUrl,source:e.publisher,date:e.publishedDate})}a.responseData.cursor&&a.responseData.cursor.pages&&(c=a.responseData.cursor.pages.length+1)}return{suggestions:b,maxPage:c}},$IS.articleProviderManager.addProvider($IS.googleNewsSearchArticleProvider))})();
(function(){"undefined"!=typeof InstantSuggest&&($IS.wikipediaArticleProvider=new $IS.ArticleProviderBase("Wikipedia","Wikipedia",[{id:"language",type:"select",label:"Language",value:"en",items:$IS.Wikipedia.languages}]),$IS.wikipediaArticleProvider.getSuggestionUrl=function(a){var b,c=a.page&&1<a.page?(a.page-1)*this.pageSize:0;b="http://{language}.wikipedia.org/w/api.php?action=query&list=search&srwhat=text&srlimit={pageSize}&sroffset={start}&format=json&srsearch={keyword}".replace("{language}",
this.preference.getOptionValue("language"));b=b.replace("{pageSize}",this.pageSize);b=b.replace("{start}",c);return b=b.replace("{keyword}",encodeURIComponent(a.keyword))},$IS.wikipediaArticleProvider.getSearchUrl=function(a){var b;b="http://{language}.wikipedia.org/w/index.php?search={keyword}&fulltext=Search".replace("{language}",this.preference.getOptionValue("language"));return b=b.replace("{keyword}",encodeURIComponent(a.keyword).replace(/%20/g,"+"))},$IS.wikipediaArticleProvider.parseSuggestions=
function(a){var b=[],c=0,d=this,e=function(a){var b;b="http://{language}.wikipedia.org/wiki/{title}".replace("{language}",d.preference.getOptionValue("language"));return b=b.replace("{title}",encodeURIComponent(a).replace(/%20/g,"+"))};if(a){if(a.query&&a.query.search)for(var f=a.query.search,g=0;g<f.length;g++){var h=f[g];b.push({title:h.title,content:h.snippet,url:e(h.title),source:d.preference.getOptionValue("language")+".wikipedia.org",date:h.timestamp})}a["query-continue"]&&a["query-continue"].search&&
this.pageSize&&(c=a["query-continue"].search.sroffset/this.pageSize+1)}return{suggestions:b,maxPage:c}},$IS.articleProviderManager.addProvider($IS.wikipediaArticleProvider))})();
(function(){"undefined"!=typeof InstantSuggest&&($IS.googleAutocompleteKeywordProvider=new $IS.KeywordProviderBase("GoogleAutocomplete","Google Autocomplete",[{id:"source",type:"select",label:"Source",value:"",items:[["Applications","apps"],["Blogs","blogs"],["Books","bo"],["Images","i"],["Maps","maps"],["News","n"],["Receipts","r"],["Shopping","sh"],["Videos","yt"],["Web",""]]},{id:"language",type:"select",label:"Language",value:"en",items:$IS.Google.languages},{id:"domain",type:"select",label:"Country",
value:"https://www.google.com",items:$IS.Google.domains}]),$IS.googleAutocompleteKeywordProvider.getSuggestionUrl=function(a){var b="";switch(this.preference.getOptionValue("source")){case "maps":b="https://maps.google.com/maps/suggest?q={keyword}&hl={language}&json=o";break;case "apps":b="https://market.android.com/suggest/SuggRequest?json=1&query={keyword}&hl={language}";break;case "blogs":b="http://suggestqueries.google.com/complete/search?q={keyword}&client=blog-hp&hl={language}&ds=blog-hp";break;
case "i":b="http://suggestqueries.google.com/complete/search?q={keyword}&client=img&hl={language}&ds=i";break;case "bo":b="http://suggestqueries.google.com/complete/search?q={keyword}&client=books&hl={language}&ds=bo";break;case "yt":b="http://suggestqueries.google.com/complete/search?q={keyword}&client=youtube&hl={language}&ds=yt";break;default:b="http://suggestqueries.google.com/complete/search?q={keyword}&client=img&hl={language}&ds={source}"}b=b.replace("{language}",this.preference.getOptionValue("language"));
b=b.replace("{source}",this.preference.getOptionValue("source"));return b=b.replace("{keyword}",encodeURIComponent(a.keyword))},$IS.googleAutocompleteKeywordProvider.getSearchUrl=function(a){var b="";switch(this.preference.getOptionValue("source")){case "maps":b="https://maps.google.com/?q={keyword}&hl={language}";break;case "blogs":b=this.preference.getOptionValue("domain")+"/search?tbm=blg&hl={language}&q={keyword}";break;case "apps":b="https://play.google.com/store/search?q={keyword}&c=apps";break;
default:b=this.preference.getOptionValue("domain")+"/search?q={keyword}&hl={language}&tbm={source}"}var b=b.replace("{language}",this.preference.getOptionValue("language")),c="";switch(this.preference.getOptionValue("source")){case "i":c="isch";break;case "sh":case "pr":c="shop";break;case "yt":c="vid";break;case "n":c="nws";break;case "bo":c="bks";break;case "blogs":c="blg";break;case "r":c="rcp";break;default:c=""}b=b.replace("{source}",c);return b=b.replace("{keyword}",encodeURIComponent(a.keyword))},
$IS.googleAutocompleteKeywordProvider.parseSuggestions=function(a){var b=[];try{switch(this.preference.getOptionValue("source")){case "maps":for(var c=0;c<a.suggestion.length;c++)b.push(a.suggestion[c].query.replace(/<\/?b>/gi,""));break;case "apps":for(c=0;c<a.length;c++)b.push(a[c].s.replace(/<\/?b>/gi,""));break;default:for(c=0;c<a[1].length;c++)b.push(a[1][c][0].replace(/<\/?b>/gi,""))}}catch(d){}return b},$IS.keywordProviderManager.addProvider($IS.googleAutocompleteKeywordProvider))})();
(function(){"undefined"!=typeof InstantSuggest&&($IS.wikipediaKeywordProvider=new $IS.KeywordProviderBase("Wikipedia","Wikipedia",[{id:"language",type:"select",label:"Language",value:"en",items:$IS.Wikipedia.languages}]),$IS.wikipediaKeywordProvider.getSuggestionUrl=function(a){var b;b="http://{language}.wikipedia.org/w/api.php?format=json&action=opensearch&search={keyword}&namespace=0&suggest=".replace("{language}",this.preference.getOptionValue("language"));return b=b.replace("{keyword}",encodeURIComponent(a.keyword))},
$IS.wikipediaKeywordProvider.getSearchUrl=function(a){var b;b="http://{language}.wikipedia.org/w/index.php?search={keyword}&fulltext=Search".replace("{language}",this.preference.getOptionValue("language"));return b=b.replace("{keyword}",encodeURIComponent(a.keyword).replace(/%20/g,"+"))},$IS.wikipediaKeywordProvider.parseSuggestions=function(a){try{return a[1]}catch(b){return[]}},$IS.keywordProviderManager.addProvider($IS.wikipediaKeywordProvider))})();
